// This component has been restored for potential batch-review functionality in the future.
// The current AI workflow uses MatchingPreviewModal for single-match confirmation.
import React from 'react';
import type { InventoryItem, ShelterNeed, AiMatch } from '../types';
import { Modal } from './Modal';

interface ReviewMatchesModalProps {
  isOpen: boolean;
  onClose: () => void;
  matches: AiMatch[];
  inventory: InventoryItem[];
  needs: ShelterNeed[];
  onConfirmMatch: (donorItemId: string, shelterNeedId: string, quantityToMatch: number) => void;
}

export const ReviewMatchesModal: React.FC<ReviewMatchesModalProps> = ({ isOpen, onClose, matches, inventory, needs, onConfirmMatch }) => {
  
  const handleConfirmAll = () => {
    matches.forEach(match => {
      onConfirmMatch(match.inventoryId, match.needId, match.quantity);
    });
    onClose();
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Review AI Recommended Matches">
      <div className="space-y-4">
        <p className="text-gray-400">Review the smart matches generated by the AI. Confirming will update inventory and beneficiary needs accordingly.</p>
        <div className="max-h-80 overflow-y-auto space-y-3 p-2 bg-gray-900 rounded-md">
            {matches.map((match, index) => {
                const item = inventory.find(i => i.id === match.inventoryId);
                const need = needs.find(n => n.id === match.needId);
                if (!item || !need) return null;

                return (
                    <div key={index} className="p-3 bg-gray-800 rounded-lg border border-gray-700">
                        <p className="font-semibold text-white">{item.name} ({match.quantity} {item.unit}) <span className="text-gray-400 mx-2">→</span> {need.shelterName}</p>
                        <p className="text-xs text-gray-500 italic mt-1">{match.reason}</p>
                    </div>
                );
            })}
        </div>
        <div className="flex justify-end space-x-3 pt-4">
          <button type="button" onClick={onClose} className="py-2 px-4 rounded-lg bg-gray-700 hover:bg-gray-600 text-white font-semibold">Cancel</button>
          <button type="button" onClick={handleConfirmAll} className="py-2 px-4 rounded-lg bg-green-500 hover:bg-green-600 text-white font-semibold">Confirm All Matches</button>
        </div>
      </div>
    </Modal>
  );
};